### ISSUE TITLE
Add hint about usage with org.eclipse.persistence:org.eclipse.persistence.jpa.modelgen.processor:2.5.2

### ISSUE THREAD

**Issue by krichter722** [ethlo/eclipselink-maven-plugin#13]
If the Maven dependency `org.eclipse.persistence:org.eclipse.persistence.jpa.modelgen.processor:2.5.2` is added (the scope doesn't seem to matter) the metamodel generation fails because of duplicate class compliation error. I assume that the presence of dependency starts a metamodel generation and then the plugin does as well. This conflict should be mentioned in the usage hints in README.

**Comment by ethlo** [comment]
Hi, and thanks for your feedback! 
Javac will look for processors that can be executed automatically (on the classpath), so this goes for any APT processor you include as a dependency. I do not see that relevance of including this, as it is a generic problem for any processor performing the same task.
