### ISSUE TITLE
Upgrade to EclipseLink 2.7.0

### ISSUE THREAD

**Issue by timomeinen** [ethlo/eclipselink-maven-plugin#14]
Version 2.7.0 of EclipseLink has been released:
https://www.eclipse.org/eclipselink/releases/2.7.php

Due to the update of javax.persistence to 2.2.0 we get errors with the current version of the plugin:

`java.lang.SecurityException: class "javax.persistence.LockModeType"'s signer information does not match signer information of other classes in the same package`

As javax.persistence is a transitive dependency of EclipseLink, it might be removed from the pom.xml.

**Comment by ethlo** [comment]
Hi, and thanks for your interest and feedback!

This plugin does support 2.7.0 (the plugin version matches the included EclipseLink library). The problem you are describing is not courtesy of this plugin, as you can read more about here: https://stackoverflow.com/questions/45870753/eclipselink-2-7-0-and-jpa-api-2-2-0-signature-mismatch. 

Hopefully, EclipseLink 2.7.1 will contain a fixed transitive dependency, with the right signature.

**Comment by timomeinen** [comment]
Thank you for your fast answer. I had a look in the wrong pom.xml of your plugin. Sorry! And thank you for the link.

**Comment by timomeinen** [comment]
We will stay with 2.6 until the signing problem is fixed.

The plugin version 2.6.4.2 uses version 2.6.4 of Eclipselink. Can we safely update to 2.6.5 or should the version in our project be in sync with Eclipselinks version defined in the plugin?

**Comment by ethlo** [comment]
I'm not sure how that would work with those versions, although I have done so successfully in the past with versions far wider apart. Just to be sure, I have released a version 2.6.5. Will be available on Maven Central in a few hours.

**Comment by timomeinen** [comment]
That's nice! Thank you.
