### ISSUE TITLE
Support for Java 10

### ISSUE THREAD

**Issue by jjesudassbah** [ethlo/eclipselink-maven-plugin#16]
Plugin fails with error when using Java 10.  Also could you please add support for jpa 2.2?

<img width="794" alt="screen shot 2018-07-05 at 3 46 09 pm" src="https://user-images.githubusercontent.com/11636077/42344557-b2d8b1fc-806a-11e8-9ddd-84a7778bba37.png">

**Comment by ethlo** [comment]
We are currently using 2.7.1.1 in a Java 11 project without issue. Please re-open if still an issue.
