### ISSUE TITLE
Check for changes before re-generating models

### ISSUE THREAD

**Issue by ghunteranderson** [ethlo/eclipselink-maven-plugin#22]
I really enjoy using the meta-model generation plugin for my build pipeline but I keep running into this issue. Sometimes Maven is ran more than once without the source code changing. In these scenarios, the Maven compiler plugin would normally detect that there were no changes and skip re-compiling the project. But with this plugin added, the meta models are re-generated which triggers a re-compile. The artifact is correct but it would be really nice if this plugin was able to "detect changes" in the source before re-generating much like the Maven compiler plugin.

Is there any interest to add this feature? If so, I can research more and begin working on a PR. I'm just looking for feedback before spending any more time on it.

**Comment by ethlo** [comment]
Hi! If you make it, I'll merge it, as long as it is stable and decent code 😊

**Comment by ghunteranderson** [comment]
Heard 😊. I'll start a little research into how other plugins solve this issue and then begin on a PR.

**Comment by ethlo** [comment]
I will close this now. Please feel free to reopen if you come up with something. Thank you.
