### ISSUE TITLE
Port eclipselink-maven-plugin to a Gradle plugin

### ISSUE THREAD

**Issue by ebenezergraham** [ethlo/eclipselink-maven-plugin#23]
Can we get an equivalent of this plugin for Gradle?

**Comment by ethlo** [comment]
Thanks for your interest in this plugin! This would be quite an undertaking and probably better off as a project of its own. I do not have the resources to do this at this time.

**Comment by ebenezergraham** [comment]
Thanks @ethlo, can you give me guidance (kind of a checklist to get me started). I will undertake this project myself.
