### ISSUE TITLE
Static-Weaving failing due to erroneous generated persistence.xml

### ISSUE THREAD

**Issue by jonnybecker** [ethlo/eclipselink-maven-plugin#26]
I just tried static-weaving with new eclipselink-maven-plugin v2.7.4.
Weaving fails since the generated persistence.xml is erroneous. The class-entries don't have the full qualified name, but the class definition.

Generated persistence.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1"
    xmlns="http://xmlns.jcp.org/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
    <persistence-unit name="regid-core" transaction-type="RESOURCE_LOCAL">
        <provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
        <properties>
            <property name="eclipselink.weaving" value="static"/>
        </properties>
        <class>public abstract class com.foo.domain.entities.BaseVersionEntity&lt;I&gt; extends com.foo.domain.entities.BaseEntity&lt;I&gt;</class>
        <class>...</class>
    </persistence-unit>
</persistence>
```

My setup:
- Windows 10
- Java 8/11
- Maven 3.5.3

**Comment by ethlo** [comment]
Thanks for the report. The issue should be fixed and is released in 2.7.4.1-SNAPSHOT

**Comment by jonnybecker** [comment]
Thanks for the quick reaction. Any release-dates for 2.7.4.1 scheduled so far?
I'm asking, since we switched to Java11 and in 2.7.1.1 static-weaving isn't working (for us?).

**Comment by ethlo** [comment]
It is released 👍

**Comment by ethlo** [comment]
Were you able to use version `2.7.4.1` with your Java 11 build?

**Comment by jonnybecker** [comment]
Seems to work, thanks a lot! But I had to add an extra dependency (bundle) for the weaving process (see below).

```
<pluginManagement>
  <plugins>
	<plugin>
	  <groupId>com.ethlo.persistence.tools</groupId>
	  <artifactId>eclipselink-maven-plugin</artifactId>
	  <version>2.7.4.1</version>
	  <dependencies>
		<dependency>
		  <groupId>org.glassfish.jaxb</groupId>
		  <artifactId>jaxb-runtime</artifactId>
		  <version>2.3.2</version>
		</dependency>
	  </dependencies>
	</plugin>
        ...
```

Which dependencies do I really need for the weaving?

**Comment by ethlo** [comment]
That should be the only one. That is due to the fact that Java 11 (9+) is
not shipping with JAXB libraries. Will consider adding it as a dependency
for the next release. Please feel free to open another issue for it. Thank
you.
