### ISSUE TITLE
Is it possible to configure the plugin not to create / update the persistence.xml file?

### ISSUE THREAD

**Issue by mattjlewis** [ethlo/eclipselink-maven-plugin#28]
In my use case I want to invoke weaving but entirely manually maintain my own persistence.xml file.

**Comment by ethlo** [comment]
It is not currently possible no. Could you please provide some details on what is the use case for this?

**Comment by mattjlewis** [comment]
I currently have an issue with my Helidon project where I have separate projects for model classes and JAX-RS service implementations so as to limit dependencies when using those model classes elsewhere. The persistence.xml file is manually maintained in the service implementation project, however, this plugin is automatically generating another one in the model classes project. I have an exclusion rule in the maven JAR plugin to exclude the autogen model persistence.xml file which results in two persistence.xml files in the classpath. However, this is not picked up within Eclipse. The result is that I am currently unable to run unit tests in Eclipse. Note, this is clearly a bug elsewhere (and I do define the unitName in every @PersistenceXXX annotation), however it would be nice to disable the persistence.xml feature in this plugin altogether.

**Comment by ethlo** [comment]
Fixed in v2.7.5.1
