### ISSUE TITLE
upgrade to 2.1

### ISSUE THREAD

**Issue by bilak** [ethlo/eclipselink-maven-plugin#3]
Hi is there any plan to upgrade to jpa 2.1?

Thanks

**Comment by ethlo** [comment]
Hi, I will look into this now. Thank you for your interest! What features are you expecting (if any) outside using 2.6.1 of eclipselink?

**Comment by bilak** [comment]
I'm not sure now why I have opened this ticket, but I think it was due to converters.

**Comment by ethlo** [comment]
I saw EclipseLink 2.5.x is already JPA 2.1 compatible. Closing.

**Comment by bilak** [comment]
Hi Ethlo,
sorry for delay. I know EL2.5 is already compatible with JPA2.1, but when you are generating orm.xml or persistence.xml there is still JPA 2.0 version. Can you please look at this?

 [here](https://en.wikibooks.org/wiki/Java_Persistence/What_is_new_in_JPA_2.1%3F) you can see what's new in JPA2.1 and there is converter. 

Thanks
