### ISSUE TITLE
Eclipse error 'You need to run build with JDK or have tools.jar on the classpath'

### ISSUE THREAD

**Issue by gorpet** [ethlo/eclipselink-maven-plugin#30]
Hi,

I'm trying to use plugin with Eclipse (2019-12) and AdoptOpenJDK (jdk-11.0.5.10-hotspot) and following error is shown on 'execution' when viewing pom.xml:

"You need to run build with JDK or have tools.jar on the classpath (com.ethlo.persistence.tools:eclipselink-maven-plugin:2.7.5.1:modelgen:default:generate-sources)"

```
<plugin>
        <groupId>com.ethlo.persistence.tools</groupId>
        <artifactId>eclipselink-maven-plugin</artifactId>
        <version>2.7.5.1/version>
          <executions>
            <execution>
              <phase>generate-sources</phase>
              <goals>
                <goal>modelgen</goal>
              </goals>
            </execution>
          </executions>
      </plugin>
```

Can you please see if there is anything I can do?

**Comment by ethlo** [comment]
Thanks for your report. I'm not sure what is going on in that case. My guess is that when running from inside Eclipse, the plugin is execting with the embedded JRE and not your expected JDK.
