### ISSUE TITLE
Plugin failed after changing asserts in tests

### ISSUE THREAD

**Issue by Captain1653** [ethlo/eclipselink-maven-plugin#35]
Hi!

I've created a simple [PR into Helidon](https://github.com/helidon-io/helidon/pull/5252), but `eclipselink-maven-plugin` failed. The classpath wasn't changed. I changed asserts in tests from JUnit to Hamcrest.

Plugin version: 2.7.9.1

How can I fix it? Any advice would be appreciated.

Kind regards

**Comment by ethlo** [comment]
Closing as the PR in Helidon is merged. No fix in this plugin.
