### ISSUE TITLE
Breaks after Spring Boot 3.1 migration

### ISSUE THREAD

**Issue by dan-graw** [ethlo/eclipselink-maven-plugin#39]
This plugin was working for Spring Boot 3.0, but after migrating to Spring Boot 3.1 I’m getting the error:
`Cannot invoke “java.util.List.size()” because genericTypes is null`
I dug into the plugin dependencies and noticed that some versions are now behind the required Spring Framework version 6.0.9, as well as others that seem outdated. Manually upgrading these dependencies did not help.

**Comment by ethlo** [comment]
Hi! Thanks for your report!

This may be due to your environment not being totally refreshed, which is a common issue when doing development with dependencies. This project is in production use on Spring Boot 3.1.x projects, so I do not believe there to be a general issue.

If you are able to, please provide an example that reproduces your issue.

**Comment by dan-graw** [comment]
I've been troubleshooting this for a couple days and still no luck. I definitely believe that it's an environment refresh issue as I've experienced that before, especially since you confirm that others are using the plugin with SB 3.1.x. I also ruled out any issues with my entity mappings. I'm not able to post any code from the project but here are my dependencies in the pom:

spring-boot-starter-data-jpa:3.1.4
spring-boot-starter-json:3.1.4
commons-lang3:3.9
commons-io:2.11.0
json-sanitizer:1.2.3
spring-security-core:6.1.1
tomcat-embed-core:10.1.11

I'm using Intellij 2022.2.3, if it's a refresh problem then do you know what I can do to fix that? I've tried rebuilding the project, removing non-essential dependency upgrades, deleting my m2 repository folder. Nothing seems to help

**Comment by ethlo** [comment]
Is this a maven or gradle project?

**Comment by dan-graw** [comment]
Maven

**Comment by ethlo** [comment]
Then I would try it from the command line directly, with mvn clean install.

**Comment by dan-graw** [comment]
I eventually figured out what was causing the error. I was putting my <basePackages> tag outside the the <executions> tag like it says in the readme. It needed to be inside the <execution> tag for the weave goal in my case (I only have the weave goal). Then it worked fine

**Comment by yatharth23112001** [comment]
I am getting same error on migrating eclipselink to 4.0.2 and the eclipse-link plugin to 3.0.2, @dan-graw can you please explain what you mean by tag and its placement, can you please help me with the right format, my current plugin looks like this:

```
<plugin>
    <groupId>com.ethlo.persistence.tools</groupId>
    <artifactId>eclipselink-maven-plugin</artifactId>
    <version>3.0.2</version>
    <executions>
        <execution>
            <phase>process-classes</phase>
            <goals>
                <goal>weave</goal>
            </goals>
        </execution>
    </executions>
  </plugin>
```
