### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by sparksis** [ethlo/eclipselink-maven-plugin#9]
Since: 
150b57a5c83c8473770f455a5c74d0814d0870bb
https://github.com/ethlo/eclipselink-maven-plugin/compare/3b0aed7d5f70...150b57a5c83c8473770f455a5c74d0814d0870bb

See also:
https://travis-ci.org/ethlo/eclipselink-maven-plugin/builds/141322116

Root Cause:
Failure to find org.scannotation:scannotation:jar:1.0.4 (Does not exist https://mvnrepository.com/artifact/org.scannotation/scannotation)

[ERROR] Failed to execute goal on project eclipselink-maven-plugin: Could not resolve dependencies for project com.ethlo.persistence.tools:eclipselink-maven-plugin:maven-plugin:2.6.3-SNAPSHOT: Failure to find org.scannotation:scannotation:jar:1.0.4 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by ethlo** [comment]
Unfortunately the scannotation project seems to be abandoned, and the latest official release does not support Java 8, thus I forked it here https://github.com/ethlo/scannotation. I will need some time to clean this up, but at least it gives you a work-around. The artifact is here: http://ethlo.com/maven/org/scannotation/scannotation/1.0.4/
